<a href="https://colab.research.google.com/github/JamesDCage/100-Challenging-Python-Problems/blob/master/DiceActions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> TheBelt </h1>
Calculations related to the game by George A. Petrick

<h2> Sky Map</h2>
Probability calculations for "sky map" game board

In [79]:
from itertools import permutations, combinations

MAX_X = MAX_Y = 12

# Create a set of all possible dice rolls (4d6)
die_rolls = [(h,i,j,k) for h in range(1,7) 
                       for i in range(1,7) 
                       for j in range(1,7) 
                       for k in range(1,7)]


In [80]:
def xy_set(roll):
    # For an individual die roll, create a set containing all possible x-y coordinates
    # Ugly code
    index_list = [0, 1, 2, 3]
    combos = list(combinations(index_list,1)) + list(combinations(index_list,2)) + list(combinations(index_list,3))
    roll_splits = [(list(c), list(set(index_list)-set(c))) for c in combos]
    coordinates = set()
    for a_split in roll_splits:
        x = y = 0
        for i in a_split[0]:
            x += roll[i]
        for j in a_split[1]:
            y += roll[j]
        if (x <= MAX_X and y <= MAX_Y):
            coordinates.add((x,y))
    return list(coordinates)


In [100]:
# Create a list of all coordinates generated after rolling all dice. 

big_list = []

for a_roll in die_rolls:
    big_list += xy_set(a_roll)

In [114]:
"""Create an array and count the number of occurences in the big list for each coordinate on the array"""
import numpy as np
count_array = np.zeros((MAX_X,MAX_Y))
for i in range(MAX_X):
    for j in range(MAX_Y):
        # print(i,j)
        count_array[i][j] = big_list.count((i+1,j+1))
print(count_array)


[[  0.   0.   1.   4.  10.  20.  34.  52.  70.  84.  90.  88.]
 [  0.   1.   4.  10.  20.  35.  56.  76.  92. 100.  96.  88.]
 [  1.   4.  10.  20.  34.  56.  70.  88.  97. 112. 106.  92.]
 [  4.  10.  20.  31.  52.  80. 100. 118. 104. 100. 112.  91.]
 [ 10.  20.  34.  52.  60. 104. 114. 124. 118. 120.  82.  92.]
 [ 20.  35.  56.  80. 104. 101. 136. 140. 124. 112.  84.  70.]
 [ 34.  56.  70. 100. 114. 136.  90. 124.  96.  76.  48.  28.]
 [ 52.  76.  88. 118. 124. 140. 124.  61.  76.  62.  36.  22.]
 [ 70.  92.  97. 104. 118. 124.  96.  76.  36.  40.  24.  16.]
 [ 84. 100. 112. 100. 120. 112.  76.  62.  40.  19.  16.  10.]
 [ 90.  96. 106. 112.  82.  84.  48.  36.  24.  16.   6.   4.]
 [ 88.  88.  92.  91.  92.  70.  28.  22.  16.  10.   4.   1.]]


In [105]:
xy_set((6,5,6,6))

[(11, 12), (12, 11)]

In [ ]:
d